### ISSUE TITLE
Abstract placement inconsistency

### ISSUE THREAD

**Issue by chbrown** [semprag/tex#2]
Some articles (e.g., sp.8.14) have **Abstract** as the first word in the first line of their abstract, while others (e.g., sp.8.13) have **Abstract** on its own line.

This depends on whether there is a blank line between `\begin{abstract}` and the content of the abstract.

I prefer the former output, where **Abstract** is not allotted its own line, but either way, we should choose one, and the behavior of the abstract environment's header should not depend on whitespace in the abstract itself.

**Comment by fintelkai** [comment]
Yes, I agree. Not a separate line. How do we force that?

**Comment by chbrown** [comment]
By absorbing `\par` and ignoring spaces.

See [before](https://github.com/semprag/semprag.github.com/blob/f84fa19/sample/test-abstract-screenshot.png) and [after](https://github.com/semprag/semprag.github.com/blob/f84fa19/sample/test-abstract.pdf) test document.
